### ISSUE TITLE
IDataReader Exception.

### ISSUE THREAD

**Issue by jbogard** [AutoMapper/AutoMapper.Data#1]
_From @elranu on January 10, 2014 17:7_

Hi, 
     Im getting the following AutoMapperMappingException. Mapping a Reader to an Entity.How I can know which is the column is generating this error?

Mapping types:
IDataReader -> UserEntity
System.Data.IDataReader -> AMSDLL.Entities.UserEntity

Destination path:
UserEntity

Source value:
System.Data.SqlClient.SqlDataReader

Thanks and Regards!

_Copied from original issue: AutoMapper/AutoMapper#441_

**Comment by jumas45** [comment]
You can try removing the columns or adding the columns one by one to find out which is the offending one. It's not ideal but you will figure out eventually.
