### ISSUE TITLE
Automapper.Mappers.DataReaderMapper is not being loaded

### ISSUE THREAD

**Issue by kdajani** [AutoMapper/AutoMapper.Data#11]
Hi,

I posted a question to Stackoverflow.com (http://stackoverflow.com/questions/30470341/datatable-to-list-automapperexception-or-values-dont-get-mapped) but I also wanted to report this here.

I'm having an issue w/ AutoMapper (3.3.1) VS 2013 Progressional, Windows 7 Professional 64bit. Setting up, I have this code:

```
// gets called in application_start
public static void ConfigureMapping() {
    // ...
    AutoMapper.Mapper.CreateMap<SubObjectClassModel, LUSubObjectClass>();
        AutoMapper.Mapper.CreateMap<LUSubObjectClass, SubObjectClassModel>()
            .ForMember(x => x.ObjectClassCode,
                y => y.MapFrom(x => x.LUObjectClass.Code))
            .ForMember(x => x.ObjectClassGroupCode,
                y => y.MapFrom(x => x.LUObjectClass.GroupCode));

   AutoMapper.Mapper.CreateMap<IDataReader, SubObjectClassModel>();
  // also tried this AutoMapper.Mapper.CreateMap<IDataReader, List<SubObjectClassModel>>();
}
```

```
public class SubObjectClassModel
    {
        public int Id { get; set; }
        public int ObjectClassId { get; set; }
        public string ObjectClassCode { get; set; }         
        public string ObjectClassGroupCode { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string ColumnDisplayName { get; set; }
        public bool IncludeInProjections { get; set; }
        public bool IncludeInFormulas { get; set; }
        public bool IsSalaryProjectionBucket { get; set; }
        public bool IsBenefitProjectionBucket { get; set; }
        public bool IsLeo { get; set; }
        public bool IsFixed { get; set; }
        public bool IsDiscretionary { get; set; }
        public string UpdatedBy { get; set; }
        public DateTime UpdatedDate { get; set; }
    }
```

```
// after running a query that returns a datatable with multiple rows. the datatable includes all fields in the Model class using ThisCasing
public static List<SubObjectClassModel> Gets()
    {
        LUSubObjectClass subObjectClass = new LUSubObjectClass();
        return Mapper.Map<IDataReader, List<SubObjectClassModel>>(
            subObjectClass.Gets().CreateDataReader()
        );
    }
```

Three scenarios occur with this issue:
-  After deploying to the server I get this error.

```
Missing type map configuration or unsupported mapping. Mapping types: IDataReader -> List`1 System.Data.IDataReader -> System.Collections.Generic.List`1[[BRS.Models.Common.SubObjectClassModel, BRS.Models, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]] Destination path: List`1 Source value: System.Data.DataTableReader
```
- When running locally, if I rebuild the entire solution, everything works fine.
- When running locally, if I make a change to the web layer and run the projection, which only rebuilds the web layer, I get an empty list back. Nothing gets mapped at all.

I have multiple objects that fit this scenario and they are all behaving the same way.

Upon further investigation I noticed the following by placing a watch on Mapper. When I do a run from VS without rebuilding the entire solution and I see no results being returned after the Mapper.Map call, I see all the mappings listed correctly under the Mapper object. However, Automappers.Mapper.DataReaderMapper is not listed under AutoMapper.ConfigurationStore.

When results are returned successfully, usually after I rebuild the solution, this mapper is listed.

What would cause that behavior and how can I ensure the DataReaderMapper gets loaded every time? 

Thanks much for your help!

**Comment by kdajani** [comment]
Anyone or any suggestions on how to fix this? How can I ensure DataReaderMapper gets loaded?

Thanks!

**Comment by jbogard** [comment]
When you deploy the app, is AutoMapper.Net4.dll deployed as well?

**Comment by kdajani** [comment]
I just created a deployment package and that dll is not in there. Only AutoMapper.dll. The project is targeting .NET Framework 4.5, Any CPU and Release mode. 

When I look at the both dll's properties in the project they appear the same: Aliases: Global, Copy Local: True, Embed Enterop Types: False.

When I look at their path [ProjectPath]packages\AutoMapper.3.3.1\lib\net40\  Both dll's are in that folder.

**Comment by jbogard** [comment]
You need to make sure the AutoMapper.Net4.dll is included in the deployment
package.

**Comment by kdajani** [comment]
OK. I'm all about that. I don't have any project settings that would exclude that from happening. I installed AutoMapper using NuGet. Why would it not just include that dll automatically? 

By the way, great tool! Thank you for it!

**Comment by jbogard** [comment]
It doesn't because MSBuild doesn't recognize the DLL being used.

Try doing something stupid like "var type = typeof(DataReaderMapper)"
somewhere, that forces the DLL to be used and copied.

**Comment by kdajani** [comment]
Finally got it to work on the server followed this recommendation:
1. Add the missing DLL to the project as a Linked File. 
2. On the file properties, Copy To Output Directory, select If Newer.

All works fine now. Thanks again!
