### ISSUE TITLE
Where do I get AutoMapper.Data?

### ISSUE THREAD

**Issue by leftler** [AutoMapper/AutoMapper.Data#13]
I tried to update from 3.3.1 to 4.0.4 and it removed AutoMapper.Net4.dll, this caused things like the workaround

```
private static readonly Type DataReaderType = typeof(AutoMapper.Mappers.DataReaderMapper);
```

discussed in issue #11 no longer work, not being able to find the `DataReaderMapper` type. I assume Automapper.Net4 is now AutoMapper.Data, but I don't see it listed on NuGet nor do I see where to download it here.

Are my assumptions incorrect that this is a 2nd library I need to download? If so where is DataReaderMapper located in 4.0.4?

**Comment by jumas45** [comment]
Automapper.Data is under Beta so when search using Visual Studio, please select to include PreRelease (not just stable) and you will find it there.

https://www.nuget.org/packages/AutoMapper.Data/1.0.0-beta1
