### ISSUE TITLE
AutoMapper.Data has no strong name

### ISSUE THREAD

**Issue by inforithmics** [AutoMapper/AutoMapper.Data#14]
I tested AutoMapper.Data the Compiler complained that it has no strong name.
This is because my Project is strongly named so Automapper.Data has to be strongly named too.

**Comment by jbogard** [comment]
Why is your project strong named? I didn't SN it because almost no one needs to SN anymore.

**Comment by inforithmics** [comment]
The reason why I have to strong name the project is a commercial 3rd party component. The License of this component is licensed to the public Key of the strong name.

**Comment by jbogard** [comment]
Would this work? https://github.com/dsplaisted/strongnamer

**Comment by inforithmics** [comment]
The nuget version of Strong Namer seems to works
