### ISSUE TITLE
No longer works with 4.2.x

### ISSUE THREAD

**Issue by bobbyangers** [AutoMapper/AutoMapper.Data#19]
Hi,
Because of the recent Interface changes, this only works with 4.1.1, not 4.2.

**Comment by jordan112** [comment]
Confirmed, we had to rollback to 4.1.1 and this fixed the issue.

**Comment by jbogard** [comment]
Yep, I need someone to step up and update it to the latest code. I don't use this library, so I won't be updating it myself.

**Comment by ColonelDuddits** [comment]
Sooooo.... I've got it updated to be compatible with AutoMapper 5.3. It took me 5 commits to get it working. Would you like me to squash them before submitting a pull request?

**Comment by jbogard** [comment]
Sure!
