### ISSUE TITLE
Failing to load assembly

### ISSUE THREAD

**Issue by MattHartz** [AutoMapper/AutoMapper.Data#24]
Hi,

I'm trying to support some legacy code that broke since our recent update to 5.0.2 of automapper.  I discovered this separate repository and installed it along with adding this code, 

`AutoMapper.Mapper.Initialize(cfg => {
    MapperRegistry.Mappers.Add(new DataReaderMapper { YieldReturnEnabled = true });
    // Other config
});` 

It immediately breaks on this code failing to load Automapper.Data.  Is this a known issue?

Thanks!

**Comment by seawerst** [comment]
Unfortunately yes, it's probably related to issue 20. This functionality has been broken since a couple of versions. If you need this mapping, I would stay with your old version.
There is a pull request from two months ago that is suppose to fix the problem.

**Comment by MattHartz** [comment]
thanks, we are reverting the project back to it's original version.

**Comment by MattHartz** [comment]
Hi @seawerst ,

Do you know what versions does this package actually work for?  I think it might be necessary to get this project to work.  Things are super busted haha.

Thanks

**Comment by jbogard** [comment]
The PR does not fix the issue - it's merely pointing AutoMapper.Data in the new repo to the 4.2.1 release. That *may* be a valid first step, but I don't think so. There's a big different in the API in 5.0 from 4.2.1.

**Comment by DaveMiscampbell** [comment]
Hey - we were actually stuck on AutoMapper 4.2.1 internally but it looks like we're ready to move 5.x so I should be able to update the PR in the near future.

**Comment by jbogard** [comment]
Cool, if you need an example, I'd look at some of the existing
IObjectMappers in the current repo. They should help point you in the right
direction.

On Wed, Nov 16, 2016 at 5:33 PM, David Miscampbell <notifications@github.com
