### ISSUE TITLE
AutoMapper.Data throwing "Cannot install package error"

### ISSUE THREAD

**Issue by rveluthattil** [AutoMapper/AutoMapper.Data#28]
Hi,

I am trying to use auto mapper (6.2.1) and when I run the code I am not having it return any results when I map it with IDataReader. Below is the code.

public class AuthorModel { 
public string Id { get; set; } 
public string FirstName { get; set; } 
public string LastName { get; set; } 
public string Address { get; set; } }

DataTable _dTable = new DataTable(); 
_dTable.Columns.Add("Id", typeof(string)); _
dTable.Columns.Add("FirstName", typeof(string)); 
_dTable.Columns.Add("LastName", typeof(string)); 
_dTable.Columns.Add("Address", typeof(string));

DataRow dRow = _dTable.NewRow(); 
_dRow["Id"] = "1"; 
_dRow["FirstName"] = "Ramachandran"; 
_dRow["LastName"] = "Veluthattil"; 
_dRow["Address"] = "ABCD EFGH IJKL"; 
_dTable.Rows.Add(dRow); dSet = new DataSet(); 
_dSet.Tables.Add(dTable);

var config = new MapperConfiguration(cfg => 
{ 
cfg.CreateMap<IDataReader, List<AuthorModel>>(); 
}); 
IMapper mapper = config.CreateMapper(); 
DataTableReader dr = _dSet.Tables[0].CreateDataReader(); 
List<AuthorModel> authors = mapper.Map<IDataReader, List<AuthorModel>>(dr); 
return authors;

I changed it to use IEnumerable and also IList but when i use those it throws an error. The code above seems to work but no results are being generated. On doing some research I found that it has been mentioned that IDataReader implementation has been moved to AutoMapper.Data and to use that package. Now when i try to add that package i get the following error and it is not adding the package

Attempting to gather dependency information for package 'AutoMapper.Data.1.0.0' with respect to project 'AutoMapper', targeting '.NETFramework,Version=v4.5' Attempting to resolve dependencies for package 'AutoMapper.Data.1.0.0' with DependencyBehavior 'Lowest' Resolving actions to install package 'AutoMapper.Data.1.0.0' Resolved actions to install package 'AutoMapper.Data.1.0.0' Install failed. Rolling back... Package 'AutoMapper.Data.1.0.0' does not exist in project 'AutoMapper' Package 'AutoMapper.Data.1.0.0' does not exist in folder 'C:\Users\rveluth\Desktop\AutoMapper\packages' Could not install package 'AutoMapper.Data 1.0.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author. ========== Finished ==========

I am using studio 2015 and version is 14.0.25431.01 update 3. The framework version is 4.6.01055.

Can you please help/advise?

**Comment by jbogard** [comment]
What version of NuGet do you have? Typically this is a NuGet client error.

**Comment by rveluthattil** [comment]
I am nuget package for visual studio and within that the version of nuget is 3.3.4.1321

**Comment by rveluthattil** [comment]
Has anybody really had this working with data reader. I have been trying this with different views posted but every time I run into some error. The latest version for automapper.data does not work with automapper6.1. I had to use the beta version and that is also not giving me any results. There are two standard results that it gives me - one is an error with GetEnumerator and when i fix that error the return count is zero - meaning i do not get any data. So does this work at all? Because I have not seen any solution with a working sample using datareader.

**Comment by jbogard** [comment]
I never used this package, which is why I pulled it out into its own
project. The tests pass but that's about all I can help with. If you get
your code working I'll be happy to take a PR.

**Comment by ColonelDuddits** [comment]
You need to call  `AddDataReaderMapping()`. This worked for me:
```
var config = new MapperConfiguration(cfg =>
{
    cfg.AddDataReaderMapping();
    cfg.CreateMap<IDataRecord, AuthorModel>();
});

IMapper mapper = config.CreateMapper();
DataTableReader dr = dSet.Tables[0].CreateDataReader();
var authors = mapper.Map<IDataReader, List<AuthorModel>>(dr);

return authors;
```

**Comment by rveluthattil** [comment]
I am using Automapper 6.2.1.0 with automapper.data version as 1.0.0.0. There is no AddDataReaderMapping() that i can see as part of the cfg variable. Please find attached the screen shot for the same.
<img width="824" alt="automapper" src="https://user-images.githubusercontent.com/16926792/33451693-6d5f6f48-d5d5-11e7-9b62-cdef8ce5addb.png">

**Comment by jbogard** [comment]
It's in the AutoMapper.Data namespace. Add "using AutoMapper.Data;"

**Comment by yaliashkevich** [comment]
Has been this issued resolved?
I still get following:
`
Retrieving package 'AutoMapper.Data 1.0.0' from 'nuget.org'.
Install failed. Rolling back...
Package 'AutoMapper.Data.1.0.0' does not exist in project 'Orthobullets.Data'
Package 'AutoMapper.Data.1.0.0' does not exist in folder 'D:\projects\orthobullets\prod-orthobullets-com\merge-websites\packages'
Executing nuget actions took 987.74 ms
install-package : Could not install package 'AutoMapper.Data 1.0.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5', but the package does not contain any assembly references or content files that are compatible 
with that framework. For more information, contact the package author.
`

**Comment by yaliashkevich** [comment]
NuGet Package Manager   4.5.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

**Comment by yaliashkevich** [comment]
From what I see here https://www.nuget.org/packages/AutoMapper.Data/
.NETFramework 4.5 is not supported. Is it intentional?

**Comment by daxu7509** [comment]
looks like you needs minimal .net 4.6.1 to use automapper.data now. .Net 4.5 won't work with standard library 1.3.

**Comment by yaliashkevich** [comment]
it looks **odd** that main package (automapper itself) supports 1.1 and this add-on starts with 1.3.
is it intentional? any plans to change this?

**Comment by jbogard** [comment]
I think I can multi-target both .NET 4.5 and netstandard1.3.

I'm targeting the lowest netstandard version I can. This package uses APIs that only exist in the 1.3 version of netstandard. That's one of the reasons I broke this out into a separate package, too.

**Comment by ColonelDuddits** [comment]
@jbogard, (insert my best Steve Urkel impression here) did I do that? If you point out which 1.3 APIs are creating problems -- or point me at a resource where I can learn to find them myself -- I'll see what I can do to align this project with AutoMapper proper.

**Comment by jbogard** [comment]
I just added .NET 4.5 support in a 1.0.1 release. No other changes to the library were made.

It's the reflection APIs that MS screwed up that are the issue. I don't feel like messing with that code, multi-targeting is easier.

**Comment by Raushansaywhat** [comment]
I fixed this problem in Visual Studio 2015 and fixed by just updating .NET Framework 4.5.2 to latest 4.7.2.
Do the below simple steps:
Step 1: Download the latest .NET Framework
https://www.microsoft.com/en-us/download/confirmation.aspx?id=56119
Step 2: Install Auto mapper from Nuget Package Manager in Visual Studio 2015
