### ISSUE TITLE
Sql time(7) type to C# TimeSpan type mapping error

### ISSUE THREAD

**Issue by promikhail** [AutoMapper/AutoMapper.Data#29]
# Hello!

I have a class:
```c#
public class Calendar {
public string Description { get; set; }
public string Name { get; set; }
public string FullDescription { get; set; }
public int PersonId { get; set; }
public string Room { get; set; }
public TimeSpan TimeBegin { get; set; }
public TimeSpan TimeEnd { get; set; }
public string TypeWorkName { get; set; }
}
```

DataReader returns columns with corresponding types:

```
NVarChar -> String,
Int -> Int,
Time(7) -> TimeSpan
```

Trying to map with:

```c#
config.CreateMap<IDataReader, Calendar>();
```

But I got error:

Value cannot be null. Parameter name: con
This error throws only when class has properties with TimeSpan type.

#### Help! How to workaround this problem?

DotNetCore 2.0
AutoMapper version 6.2.1,
AutoMapper.Data version 1.0.0

**Comment by ColonelDuddits** [comment]
The cause of this error is that the `TimeSpan` struct doesn't have a default constructor. You should be able to work around this by configuring a type converter (see https://github.com/AutoMapper/AutoMapper/wiki/Custom-type-converters) or a value resolver (see https://github.com/AutoMapper/AutoMapper/wiki/Custom-value-resolvers).

**Comment by promikhail** [comment]
@ColonelDuddits, thanks! I will explore this.

**Comment by ColonelDuddits** [comment]
Actually, it would be much simpler to use a custom member mapping like so:
```C#
cfg.CreateMap<IDataRecord, DtoWithTimeSpanProperty>()
    .ForMember(dest => dest.TimeBegin, 
        options => options.MapFrom(src => TimeSpan.Parse(src.GetString(5))));
```
