### ISSUE TITLE
Automapper.Data doesn't work with Automapper version 6.2.2

### ISSUE THREAD

**Issue by daxu7509** [AutoMapper/AutoMapper.Data#30]
Hi,
I used the latest automapper from nuget (v 6.2.2) together with automapper.data, everything compiles, but when running, it throws this error:
Method not found: 'System.Linq.Expressions.Expression AutoMapper.Mappers.Internal.CollectionMapperExpressionFactory.MapItemExpr(AutoMapper.IConfigurationProvider, AutoMapper.ProfileMap, AutoMapper.PropertyMap, System.Type, System.Type, System.Linq.Expressions.Expression, System.Linq.Expressions.ParameterExpression ByRef)'.

I tried with the automapper.data.tests project and got the same error if I upgrade automapper to 6.2.2.

Can you have a look?

Many Thanks

**Comment by liaowubinf** [comment]
I found this Bug too, when 6.2.2, it throws Method not found, it running well when with 6.2.1

**Comment by mforhadhossain** [comment]
Any update on this?

**Comment by gdemartini** [comment]
Hit this issue too. Anyone managed to solve it?

**Comment by gdemartini** [comment]
Looking at the source code I could see that 6.2.2 introduces some interface breaking changes, i.e., it's not backwards compatible. AutoMapper.Data doesn't compile if you update the reference to 6.2.2.

**Comment by gitmadness** [comment]
I'm still hitting the problem on 7.0.1.

**Comment by lbargaoanu** [comment]
A PR is welcome.
