### ISSUE TITLE
.Map<IDataReader, FooDto> not mapping custom ForMember

### ISSUE THREAD

**Issue by paultechguy** [AutoMapper/AutoMapper.Data#35]
All but one of my DTO members are mapped fine, but the one with a different property name (ForMember) doesn't get mapped.

I have a DTO class:

```
public class FooDto
{
   ...
   public string UserId {get; set;}
}
```

My database record has a string column "Id" that I want to map into FooDto, UserId.  My configure includes:

```
CreateMap<IDataReader, FooDto>()
   .ForMember(dest => dest.UserId, opt => opt.MapFrom(src => src.GetString(src.GetOrdinal("Id"))));
```

When I call:
```
var records = mapper.Map<IDataReader, IEnumerable<FooDto>>(reader);
```

The records include the value for all properties except the "Id" column.  In fact, I can do this and my records are still missing a value:

```
CreateMap<IDataReader, FooDto>()
   .ForMember(dest => dest.UserId, opt => opt.MapFrom(src => "abc")));
```

I don't think the ForMember code is being executed at all during the IDataReader mapping.  Any ideas?

Using AutoMapper 7.0.1 and AutoMapper.Data 2.0.0.

**Comment by paultechguy** [comment]
This does work, if I iterate over the reader with Read() and read/map a single record at a time with an IDataRecord (rather than an IDataReader).  So I'm assuming the IDataReader doesn't support ForMember mappings.

**Comment by DekkersR** [comment]
Hi, have you already found a solution for this issue. I currently have the same issue.

My setup (i'm using DI (unity)):
```container.RegisterInstance<IMapper>(new AutoMapperConfiguration().Configure().CreateMapper());```

```
public class AutoMapperBootstrap : Profile 
{
    public AutoMapperBootstrap()
    {
        CreateMap<IDataReader, DtoObject>()
            .ForMember(dest => dest.SomeField, opt => opt.MapFrom(src => src.GetDateTime(src.GetOrdinal("OtherField"))));
    }
}
```

```
public class AutoMapperConfiguration
{
    public MapperConfiguration Configure()
    {
        var config = new MapperConfiguration(cfg =>
        {
            cfg.AddDataReaderMapping();
            cfg.AddProfile<AutoMapperBootstrap>();
        });
        return config;
    }
}
```

**Comment by paultechguy** [comment]
I never solved it.  I really don't think the IDataReader is fully complete and fits with the rest of AutoMapper.  For me, I didn't even have to add a configuration for IDataReader for my DTO.  I included the AutoMapper.Data NuGet and I did however do something like this, reading individual rows from the reader:

```
	while(await reader.ReadAsync())
	{
		var user = _mapper.Map<IDataReader, UserDto>(reader);

		// fields not mapped because bug in IDataReader
		SetUnmapppedFromReader(reader, user);
	}
```
Where setUnmappedFromReader sets a few of my DTO properties with different names than the DB columns, manually with:

dto.property = (string)reader["MyColumnName"];

Totally bad, but was the only way to get things working.  This was all the result of having to call an SPROC for results rather than Entity Framework.

Good luck.

**Comment by ColonelDuddits** [comment]
Have you tried `cfg.CreateMap<IDataRecord, FooDto>()`?

**Comment by paultechguy** [comment]
Yes, I've tried IDataRecord as well.  I basically found no way the AutoMapper.Data would read custom mappings from a cfg.CreateMap.  Would love to be incorrect in this so if anyone can find a solution, that would be awesome.

**Comment by ryno1234** [comment]
I too have tried `cfg.CreateMap<IDataRecord, FooDto>()`, my lambda expression within `opt => opt.ResolveUsing(...lambda expression)` gets hit during the actual mapping of my IDataReader to my DTO and I correctly resolve the value, yet it appears that the resolved value does not get used because I'm getting an exception immediately after my `ResolveWith` call saying that the source value cannot be cast to the destination value, despite the fact that I already correctly converted the value.

**Comment by paultechguy** [comment]
This also sounds familiar in my journey.  I'm a bit confused that this doesn't work as so many other posts and examples show it working...and yet it doesn't.  I wonder if an EF release or AutoMapper release has broken this functionality.

I would truly love to use IDataReader or IDataRecord since this would really help with custom data sets being returned from things like a sql stored procedure.  For now, I'm forced to do old style field-to-field mapping when using stored procedures for a few performance-centric queries.

**Comment by jbogard** [comment]
There's a reason why I moved this to a different repository - if people want new features, they need to add them. I'm happy to take PRs, but I don't really add stuff because I don't use this project.

**Comment by ColonelDuddits** [comment]
Here's a [branch in my fork](https://github.com/ColonelDuddits/AutoMapper.Data/tree/Issue35) where I tried to reproduce the issue. It works as expected for me. Can you pull that and let me know whether or not it:
a) accurately reflects what you are trying to do and
b) works

The relevant tests are `When_mapping_a_data_reader_to_FooDto_with_a_literal_value` at line 602 and `When_mapping_a_data_reader_to_FooDto_with_a_column_value` at line 630.

**Comment by paultechguy** [comment]
OK, I seem to have figured this out.  If you notice my DI stuff in ConfigureServices:

```
// auto mapper
services.AddAutoMapper(action =>
{
	// Enable so we can use AutoMapper.Data and leverage ADO.Net IDataReader and IDataRecord
	action.AddDataReaderMapping(enableYieldReturn: false);

	action.AddProfile<AutoMapperProfileConfigure>();
});

```
The problem, for whatever reason, is the AddProfile call.  I spotted a comment somewhere that said AutoMapper will scan all derived Profile classes and add them...so I removed the AddProfile  and it now works.  Crazy but I'm thrilled.

Thanks ColonelDuddits for the tests and helping out.

**Comment by paultechguy** [comment]
Ug...I closed too early.  The data reader is working, but the custom fields still are not mapped.

**Comment by paultechguy** [comment]
Also see [this issue](https://github.com/AutoMapper/AutoMapper/issues/2043).

**Comment by ColonelDuddits** [comment]
@paultechguy I've added an entire unit test project for DI to [my branch](https://github.com/ColonelDuddits/AutoMapper.Data/tree/Issue35). It works for me with and without AddProfile. Is it possible that the `IMapper` instance you are invoking `Map` on isn't the same one you configured with the profile?

**Comment by paultechguy** [comment]
I'm not using AddProfile either:

```
services.AddAutoMapper(action =>
{
	action.AddDataReaderMapping();
}, typeof(AutoMapperProfileConfigure));

```

I know the the IMapper I'm using with DI is the one with my Map, because I wasn't getting any maps results (all defaults), but when I modified my Map to explicitly map each DTO member, then it gave me good results.  The only downside is that I have to map every field, even ones with the same member name.

This is a .NET Core console app with:

```
AutoMapper 7.0.1
AutoMapper.Data 2.0.0
AutoMapper.Extensions.Microsoft.DependencyInjection
```

**Comment by paultechguy** [comment]
ColonelDuddits, sorry for the delay as I'm in a conference this week.

Just to clarify we're on the same page.  My code works as long as I explicitly CreateMap and do a ForMember on every DTO member property I want mapped in my DTO.  If I don't explicitly ForMember a DTO member, it won't be mapped by the IDataReader CreateMap.  You can see this in action by adding **BigInteger** to your test Foo class:

```
public class Foo
{
	public string FirstName { get; set; }
	public string LastName { get; set; }
	public int BigInteger { get; set; }
}

```
Then when you run a test, after:

    Result = mapper.Map<IDataReader, IEnumerable<Foo>>(dataReader).FirstOrDefault();

Result.**BigInteger** will have the default (unmapped) value of 0.  Maybe I am incorrect, but I was hoping that DTO members without an explicit ForMember, but have the same name as a DataReader column name, would be mapped by default...like the standard AutoMapper feature.

**Comment by ColonelDuddits** [comment]
Well, *that's* interesting... I am able to reproduce that result. I'm looking into it.

**Comment by ColonelDuddits** [comment]
I know the root cause now. I'll submit a PR later to fix it. In the meantime you can add `AddMemberConfiguration().AddMember<DataRecordMemberConfiguration>();` to your `Profile` constructor and things should start mapping as expected.

**Comment by paultechguy** [comment]
OK, adding the AddMemberConfiguration appears to have fixed things so members with like-names are automatically mapped.  Great job on your end!  I'll be keen to see the PR.  Take care and much appreciated.  Maybe I'll want until we can see the PR, add it to this issue, then I can close things out.  Take care.

**Comment by ask-imran** [comment]
Is this fixed?
Like, am having issues for not mapping custom ForMember.
could someone throw some light?

**Comment by AleAuthenticGaming** [comment]
I've bypassed this issue by adding a mapping on IDataRecord.

`                            cfg.CreateMap<IDataRecord, Language>()
                                .ForMember(dest => dest.TwoLetterISOCode, opt => opt.MapFrom(src => (string)src["two_letter_iso"]))
                                .ForMember(dest => dest.ThreeLetterISOCode, opt => opt.MapFrom(src => (string)src["three_letter_iso"]));

                            cfg.CreateMap<IDataReader, Language>();
`

I've created the projection for the properties with a different name from the db field and it works correctly now

**Comment by franconet84** [comment]
> I know the root cause now. I'll submit a PR later to fix it. In the meantime you can add `AddMemberConfiguration().AddMember<DataRecordMemberConfiguration>();` to your `Profile` constructor and things should start mapping as expected.

Thanks a lot, yuo really save my all day, I spent 2 days loking for the solution. keep doing it.

------- with the line works

public class MappingProfile : Profile
    {
        public MappingProfile()
        {            
            AddMemberConfiguration().AddMember<DataRecordMemberConfiguration>();
            CreateMap<IDataRecord, DTOModel>();            
        }
    }

**Comment by iulian0512** [comment]
> I know the root cause now. I'll submit a PR later to fix it. In the meantime you can add `AddMemberConfiguration().AddMember<DataRecordMemberConfiguration>();` to your `Profile` constructor and things should start mapping as expected.

thank you for this workaround, spent hours, still not fixed in automapper.data 4.1.0 with automapper 9.0
