### ISSUE TITLE
Automapper version 2.2 giving Access Violation exception on Windows Azure Website

### ISSUE THREAD

**Issue by TariqAshraf** [AutoMapper/AutoMapper.Data#39]
We are using automapper version 2.2 in our website which is hosted in windows azure websites . On October 21, 2016 automapper started throwing AccessViolation Exception on some places in our website, before that it was working fine. 
We need help in this regard.

**Comment by jbogard** [comment]
@swatiAga I transferred the issue to the correct repo. I'll accept PRs to fix this problem.
