### ISSUE TITLE
Mapping to byte array property throws ArgumentNullError

### ISSUE THREAD

**Issue by MatyushovAnton** [AutoMapper/AutoMapper.Data#40]
Hello!
I'm using AutoMapper.Data package and trying to map from IDataReader to my DTO object, containing byte[] property. 
When I call extension method AddDataReaderMapping(), it throws ArgumentNullExpression, due to  argument "con" of ILGenerator's method Emit, that your DataRecordMemberConfiguration class calls, is null. That's right, because byte array hasn't parameterless ctor.

**Comment by jbogard** [comment]
PR is welcome! I don’t really maintain this package any more.

**Comment by AgentFire** [comment]
@lbargaoanu sorry for stupid question, but how can I find out from this very thread which AutoMapper version will already contain the committed change(s)?

**Comment by lbargaoanu** [comment]
This is not AutoMapper proper. I know very little about this project.

**Comment by ColonelDuddits** [comment]
@lbargaoanu, any idea when this will be available via nuget?

**Comment by lbargaoanu** [comment]
No, not really.
