### ISSUE TITLE
AutoMapper v9.0 vs AutoMapper.Data v4.0

### ISSUE THREAD

**Issue by vietlp** [AutoMapper/AutoMapper.Data#45]
When try to upgrade to the latest versions, I got the issue. The enumerable data has elements but element's data field is always empty.

My configs are below:

```c#
services.AddAutoMapper(cfg => {
                cfg.AddDataReaderMapping(false);
                cfg.AllowNullCollections = false;
                cfg.AllowNullDestinationValues = true;
            }, typeof(Startup));
```

```c#
public class UserMappingProfile : Profile
        {
            public UserMappingProfile()
            {
                CreateMap<IDataReader, User>();
            }
        }
```
And try to map to DTO:

```c#
using (var reader = (await ExecuteSqlQueryAsync(databaseFacade, sql, parameters)).DbDataReader)
            {
                var data = mapper.Map<IDataReader, IEnumerable<T>>(reader);
            }
```

The `data.Count` > 0 but all element's fields are default values.

**Comment by vietlp** [comment]
After removing `UserMappingProfile` class, and add the mapping as below:
`services.AddAutoMapper(cfg => {
                cfg.AddDataReaderMapping(false);
                cfg.CreateMap<IDataReader, User>();
                cfg.AllowNullCollections = false;
                cfg.AllowNullDestinationValues = true;
            }, typeof(Startup));`

It works perfectly!

**Comment by gssjr** [comment]
Is this a bug? Shouldn't using that external Profile class work?
