### ISSUE TITLE
Please provide PDBs

### ISSUE THREAD

**Issue by siegfriedpammer** [AutoMapper/AutoMapper.Data#46]
I just started using AutoMapper.Data and I am trying to figure out how to map `IDataReader` to arbitrary `T`s dynamically/at runtime.

The exceptions I receive are often very cryptic and it would help a lot, if there was a symbol package (snupkg) or similar available. It would make debugging these exceptions a lot easier and help me figure out what AutoMapper is expecting.

Thank you!

**Comment by lbargaoanu** [comment]
Source link can help with that. A PR is welcome.
