### ISSUE TITLE
.Map is not working with IDataReader

### ISSUE THREAD

**Issue by FelixStumvoll** [AutoMapper/AutoMapper.Data#49]
I'am currently trying to map the output of a IDataReader to a Dto, but no Properties are being mapped.
My Mapper Config looks like this:
```
var mapperConfig = new MapperConfiguration(cfg =>
            {
                cfg.CreateMap<IDataReader, Country>();
            });
```
And The Country looks like this:

```
public class Country : IDbEntity {
        public int Id { get; set; }
        public string Name { get; set; }
    }
```

To Map the Dtos im using the `.Map` function like this: 

```
await using var reader = await command.ExecuteReaderAsync();
                while (reader.Read())
                {
                    items.Add(Mapper.Map<T>(reader));
                }
```

In my database the country has the columns **id** and **name**
However AutoMapper doesn't map the properties. And i'm also not getting any error message

It works if i manually configure it with `.ForMember`, but there isn't much auto in that.

**Comment by evsheffield** [comment]
In your mapper config are you calling `AddDataReaderMapping()`?

e.g.
```
var mapperConfig = new MapperConfiguration(cfg =>
            {
                cfg.AddDataReaderMapping();
                cfg.CreateMap<IDataReader, Country>();
            });
```

When I was trying out this extension I noticed that without this line none of the properties got mapped automatically.
