### ISSUE TITLE
IDataReader mapper not applying Custom Type Converter

### ISSUE THREAD

**Issue by ShayanZafar** [AutoMapper/AutoMapper.Data#53]
Hello, 

I have the following code
```
      mapper = new Mapper(
                new MapperConfiguration(x =>
            {
                x.CreateMap<System.Decimal, System.String>()
                    .ConvertUsing( d => Convert.ToString(d));
                // DataReaderMappings
                x.AddDataReaderMapping();
                x.CreateMap<IDataRecord, TypeWithStringProperties>();
```

In my DB there are some numeric types which are being resolved to Decimal coming in. Instead of casting on the db side i thought i could simply define a converter using automapper to call the C# native wrapper class method ToString() method to convert the decimal to the string property in the 'TypeWithStringProperties' object.

However, I am noticing that the custom type converter is not applying my mapping from decimal to string in the IDataRecord to TypeWithStringProperties mapping. 

Is there something I am doing incorrectly? or this a bug?

**Comment by ASauchanka** [comment]
Any updates on that?
