### ISSUE TITLE
The AutoMapper.Data 4.1.0 is incompatible with AutoMapper 10.0.0.

### ISSUE THREAD

**Issue by Ran-snow** [AutoMapper/AutoMapper.Data#56]
When AutoMapper is updated 10.0.0 , The AutoMapper.Data doesn't work properly
> System.TypeLoadException : Method 'MapDestinationPropertyToSource' in type 'AutoMapper.Data.Configuration.Conventions.DataRecordMemberConfiguration' from assembly 'AutoMapper.Data, Version=4.1.0.0, Culture=neutral, PublicKeyToken=c81663b416b68723' does not have an implementation.

···
 ConfigurationExtensions.AddDataReaderMapping(IMapperConfigurationExpression configuration, Boolean enableYieldReturn)
    <>c__7`1.<MapTo>b__7_1(IMapperConfigurationExpression cfg) 行 162
    MapperConfiguration.Build(Action`1 configure)
    MapperConfiguration.ctor(Action`1 configure)
    <>c__7`1.<MapTo>b__7_0() 行 160
···

I don't know what to do. 😭

**Comment by lbargaoanu** [comment]
A PR is welcome.

**Comment by Ran-snow** [comment]
I will try to modify this. 😁
