### ISSUE TITLE
Opcodes using a short-form index cannot address a local position over 255

### ISSUE THREAD

**Issue by Fluttercom** [AutoMapper/AutoMapper.Data#58]
Got an interesting issue here:
```
MapperConfiguration config = new MapperConfiguration(c => 
{
   c.AddDataReaderMapping();
   c.CreateMap<IDataReader, HugeClass>()
      .ForMember(dest => dest.Id, opt = opt.MapFrom(src => Convert.ToInt32(src["Id"])))
      .ForAllOtherMembers(o => o.Ignore());
});
config.AssertConfigurationIsValid();
```
HugeClass is a class with a lot of nested properties.
Configuration fails with exception 'Opcodes using a short-form index cannot address a local position over 255' in EmitPropertyMapping.
We get this exception because all il.DeclareLocal() calls come within one context and it does not support more than 255 variables.

I understand it is not a best practice to use such big classes, but what surprised me is that AutoMapper generates IL for all properties, even if we set them to Ignore. That doesn't look optimal to me.

**Comment by lbargaoanu** [comment]
A PR is welcome.

**Comment by Fluttercom** [comment]
Ok, would try to work on it.

**Comment by Fluttercom** [comment]
Actually in this particular case we can skip AddDataReaderMapping call, since we don't use any Automapper.Data functionality.
I still think that DataRecordMemberConfiguration is not very correct place to generate dynamic methods, but this would be a big change, don't wanna do it.
I think the issue might be closed.
