### ISSUE TITLE
Cannot map an integer DataTable Column in a long Dto property

### ISSUE THREAD

**Issue by AndreaA86** [AutoMapper/AutoMapper.Data#59]
I have a table in SQLServer with a int column.
I cannot map this int column in my Dto class with long property. I have an InvalidCastException.

How can I solve this issue without explicitly casting each source element to be mapped using forMember?
Etc. something like ForAllMembers()..Condition...Resolve?!?!

Thanks for help.

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow.
