### ISSUE TITLE
Readme incorrect for initialization

### ISSUE THREAD

**Issue by FastTracOnline** [AutoMapper/AutoMapper.Data#69]
The readme explicitly suggests to use DI and AddAutoMapper(typeof(Startup), ...

I have the latest AutoMapper (12.0.1), AutoMapper.Data (7.0.2), AutoMapper.Extensions.Microsoft.DependencyInjection (12.0.1) and there is no such signature for AddAutoMapper().

I am having all sorts of grief trying to access DB2 using DB2DataReader (inherits IDataReader & IDataRecord interfaces) and mapping to a POCO, one record at a time.  I have not found anything useful / working doing Google searches.  Everything is either old (DataReader in 3.1.1) or requires an in-memory implementation (not feasible with 100million+ records).

**Comment by lbargaoanu** [comment]
A PR is welcome.
