### ISSUE TITLE
Define generic Type Converter

### ISSUE THREAD

**Issue by stefanzilik-shell** [AutoMapper/AutoMapper.Data#70]
Hi,

any way to define generic Type converter, e.g. from string to int, like here https://docs.automapper.org/en/stable/Custom-type-converters.html 
`cfg.CreateMap<string, int>().ConvertUsing(s => Convert.ToInt32(s));`

Reason for this is that the source DataTable contains all data as strings, and the destination PoCo(s) are strongly typed, so conversion is needed, and it would be productive to avoid having to define custom conversion for each property explicitely

Current behaviour:
AutoMapperMappingException: Error mapping types.
InvalidCastException: Unable to cast object of type 'System.String' to type 'System.Int32'.

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow.

**Comment by stefanzilik-shell** [comment]
AutoMapper.Data does not seem to observe Converters so if it's deficiency in this repo code base how is StackOverflow going to help?

**Comment by lbargaoanu** [comment]
Then a PR is welcome.
