### ISSUE TITLE
Is there a way the lib can work in AOT mode

### ISSUE THREAD

**Issue by jerryxu1234** [AutoMapper/AutoMapper.Data#75]
hi,
We use automapper.data in our project and it works quite well. Now I am experimenting the idea of publishing our project in AOT mode, After adding these in our project file and run our code

	  <RuntimeIdentifiers>linux-x64</RuntimeIdentifiers>
	  <PublishAot>true</PublishAot>

We got this error 
![image](https://github.com/user-attachments/assets/c54d33a1-b360-413f-9de8-2a89083a6f61)
so looks like automapper.data won't work in AOT mode, is there a way to walk around this, so automapper.data can run in AOT?

Thanks

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow.
