### ISSUE TITLE
SourceNamingConvention and DestinationNamingConvention does not work.

### ISSUE THREAD

**Issue by Nizio-Dev** [AutoMapper/AutoMapper.Data#76]
In my case I have Snowflake ADO.NET DataReader, which implements IDataReader.

My destination DTO contains property "SourceId". Reader contains column "source_id".

Setting SourceNamingConvention to LowerUnderscore convention doesn't work. AutoMapper.Data still tries to read "SourceId".

**Comment by Nizio-Dev** [comment]
#71 This is related to this. I don't know why the previous issue was closed

**Comment by lbargaoanu** [comment]
A PR is welcome.
