### ISSUE TITLE
Cache Ordinal position and reuse in DataReaderHelper's TryGetValue?

### ISSUE THREAD

**Issue by jerryxu1234** [AutoMapper/AutoMapper.Data#78]
hi,

In TryGetValue function of DataReaderHelper.cs, this is the code
try
            {
                value = dataRecord[fieldName];
                return true;
            }
Wouldn't it be good if the Ordinal position of the field can be remembered and reused? We use automapper.data quite extensively in our project. From a production profiler trace, we can see that DataReaderHelper.TryGetValue is the most CPU entensive call.

dataRecord[fieldName] internally is split into two operation by c#, first to get ordinal and then use ordinal to get value.

It would be really good if ordinal position can be remembered and reused.

**Comment by lbargaoanu** [comment]
A PR is welcome.
